version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: dental
            POSTGRES_USER: dental
            POSTGRES_DB: dental
        ports:
            - "5432:5432"
    backend:
        build: ./
        ports:
            - "3090:3090"
        links:
            - db
        env_file: .env
    frontend:
        build: ../dentalhq-front-end
        ports:
            - "3000:3000"
        env_file: ../dentalhq-front-end/.env
        links:
            - backend